import type { ArticleCatalogEntry } from "./schema";

export const ARTICLE_CATALOG: ArticleCatalogEntry[] = [
  {
    id: "longer-pollen-seasons",
    slug: "longer-pollen-seasons",
    publishedAt: "2026-04-09",
    updatedAt: "2026-04-09",
    featured: true,
    priority: 100,
    theme: "green",
    tags: ["climate", "seasonality", "forecast"],
    sourceIds: [
      "cdc-allergens-pollen",
      "acaai-worse-every-year",
      "kdca-pollen-guide",
    ],
    relatedIds: [
      "forecast-vs-count-pollen",
      "pollen-dust-heat-days",
      "adult-onset-allergy-after-moving",
    ],
  },
  {
    id: "forecast-vs-count-pollen",
    slug: "forecast-vs-count-pollen",
    publishedAt: "2026-04-09",
    updatedAt: "2026-04-09",
    featured: true,
    priority: 96,
    theme: "blue",
    tags: ["forecast", "behavior", "planning"],
    sourceIds: ["aaaai-hay-fever", "kma-life-index", "kma-pollen-index-table"],
    relatedIds: [
      "outdoor-timing-on-high-pollen-days",
      "longer-pollen-seasons",
      "when-allergies-need-a-clinic-plan",
    ],
  },
  {
    id: "pollen-dust-heat-days",
    slug: "pollen-dust-heat-days",
    publishedAt: "2026-04-09",
    updatedAt: "2026-04-09",
    featured: true,
    priority: 94,
    theme: "amber",
    tags: ["air-quality", "heat", "combined-risk"],
    sourceIds: [
      "cdc-pollen-health",
      "cdc-allergens-pollen",
      "pubmed-pollution-review",
    ],
    relatedIds: [
      "home-hepa-pollen-routine",
      "outdoor-timing-on-high-pollen-days",
      "eye-allergy-reset",
    ],
  },
  {
    id: "eye-allergy-reset",
    slug: "eye-allergy-reset",
    publishedAt: "2026-04-09",
    updatedAt: "2026-04-09",
    featured: false,
    priority: 92,
    theme: "rose",
    tags: ["eyes", "symptoms", "conjunctivitis"],
    sourceIds: ["aaaai-eye-allergy", "kdca-eye-allergy", "cdc-pollen-health"],
    relatedIds: [
      "home-hepa-pollen-routine",
      "pollen-dust-heat-days",
      "when-allergies-need-a-clinic-plan",
    ],
  },
  {
    id: "pollen-food-syndrome",
    slug: "pollen-food-syndrome",
    publishedAt: "2026-04-09",
    updatedAt: "2026-04-09",
    featured: false,
    priority: 90,
    theme: "green",
    tags: ["food", "cross-reactivity", "oral-allergy"],
    sourceIds: ["acaai-pfas", "aaaai-outdoor-allergens", "kdca-pollen-guide"],
    relatedIds: [
      "longer-pollen-seasons",
      "when-allergies-need-a-clinic-plan",
      "adult-onset-allergy-after-moving",
    ],
  },
  {
    id: "thunderstorm-asthma-alert",
    slug: "thunderstorm-asthma-alert",
    publishedAt: "2026-04-09",
    updatedAt: "2026-04-09",
    featured: false,
    priority: 88,
    theme: "amber",
    tags: ["storm", "asthma", "acute-risk"],
    sourceIds: [
      "pubmed-thunderstorm-2025",
      "pubmed-thunderstorm-2026",
      "aaaai-exercise-asthma",
    ],
    relatedIds: [
      "pollen-dust-heat-days",
      "outdoor-timing-on-high-pollen-days",
      "when-allergies-need-a-clinic-plan",
    ],
  },
  {
    id: "home-hepa-pollen-routine",
    slug: "home-hepa-pollen-routine",
    publishedAt: "2026-04-09",
    updatedAt: "2026-04-09",
    featured: false,
    priority: 86,
    theme: "blue",
    tags: ["home", "hepa", "indoor-air"],
    sourceIds: ["epa-hepa", "epa-air-cleaners", "cdc-pollen-health"],
    relatedIds: [
      "eye-allergy-reset",
      "pollen-dust-heat-days",
      "outdoor-timing-on-high-pollen-days",
    ],
  },
  {
    id: "outdoor-timing-on-high-pollen-days",
    slug: "outdoor-timing-on-high-pollen-days",
    publishedAt: "2026-04-09",
    updatedAt: "2026-04-09",
    featured: false,
    priority: 84,
    theme: "green",
    tags: ["routine", "exercise", "timing"],
    sourceIds: [
      "aaaai-outdoor-allergens",
      "aaaai-exercise-asthma",
      "kma-life-index",
    ],
    relatedIds: [
      "forecast-vs-count-pollen",
      "pollen-dust-heat-days",
      "thunderstorm-asthma-alert",
    ],
  },
  {
    id: "when-allergies-need-a-clinic-plan",
    slug: "when-allergies-need-a-clinic-plan",
    publishedAt: "2026-04-09",
    updatedAt: "2026-04-09",
    featured: false,
    priority: 82,
    theme: "rose",
    tags: ["medication", "allergist", "care"],
    sourceIds: [
      "acaai-seasonal-allergies",
      "kdca-pollen-guide",
      "aaaai-hay-fever",
    ],
    relatedIds: [
      "forecast-vs-count-pollen",
      "eye-allergy-reset",
      "thunderstorm-asthma-alert",
    ],
  },
  {
    id: "adult-onset-allergy-after-moving",
    slug: "adult-onset-allergy-after-moving",
    publishedAt: "2026-04-09",
    updatedAt: "2026-04-09",
    featured: false,
    priority: 80,
    theme: "gray",
    tags: ["adult-onset", "moving", "sensitivity"],
    sourceIds: [
      "acaai-who-gets-allergies",
      "acaai-worse-every-year",
      "aaaai-outdoor-allergens",
    ],
    relatedIds: [
      "longer-pollen-seasons",
      "pollen-food-syndrome",
      "when-allergies-need-a-clinic-plan",
    ],
  },
];
